### ISSUE TITLE
Error loading template 'gcode_macro BEACON_APPLY_MULTIPLIER:gcode'

### ISSUE THREAD

**Issue by sauyri** [YanceyA/BeaconPrinterTools#3]
I did everything that https://github.com/YanceyA/BeaconPrinterTools/blob/main/Tools/Thermal_Expansion_Compensation/Thermal_expansion_compensation.md said to do in the Pre-Reqs and Setup steps and i'm now getting this error

After copying the config from latest version into my setup i get the following error: 

![Screenshot 2024-06-21 201855](https://github.com/YanceyA/BeaconPrinterTools/assets/57909519/7ba8c653-9439-4ce2-8b17-5b1326284dd2)

**Comment by Kizime123** [comment]
https://github.com/YanceyA/BeaconPrinterTools/commit/07274415791e2f52fa280da1c9170ca41cdb6a9c did a commit to fix this issue, was an accidental | remaining should work now.
