### ISSUE TITLE
Missing Print_end macro

### ISSUE THREAD

**Issue by DrFate09** [YanceyA/BeaconPrinterTools#6]
I'm new to this repository, is the Print_end macro suppose to be missing? It is called out in the README.md but it does not link to any config file. 

Thanks 🙂

**Comment by YanceyA** [comment]
@DrFate09 I added a print_end macro which is just taken from the Voron V2 sample configuration. There are really no beacon specific actions or features to do during print_end so a more generic macro will suffice.

https://github.com/YanceyA/BeaconPrinterTools/blob/main/Config/Print_end/Print_end.md
